"""initial tables

Revision ID: 52bda7cd3cfa
Revises: 
Create Date: 2026-06-21 10:35:45.210426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bda7cd3cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('fixed_amount', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_no', sa.String(length=20), nullable=True),
    sa.Column('ceo_name', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('business_item', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tax_invoice_email', sa.String(length=100), nullable=True),
    sa.Column('vat_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_accounts',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('holder', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=10), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('team_leader', sa.String(length=50), nullable=True),
    sa.Column('base_pay', sa.Integer(), nullable=True),
    sa.Column('ot_pay', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=10), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('incheon_airport_fee', sa.Integer(), nullable=True),
    sa.Column('gimpo_airport_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('client_id', sa.String(length=10), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('start_datetime', sa.String(length=20), nullable=True),
    sa.Column('end_datetime', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.String(length=10), nullable=True),
    sa.Column('account_subject_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=10), nullable=True),
    sa.Column('driver_id', sa.String(length=10), nullable=True),
    sa.Column('receipt_type', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['account_subject_id'], ['account_subjects.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_orders',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('quote_id', sa.String(length=10), nullable=True),
    sa.Column('client_id', sa.String(length=10), nullable=False),
    sa.Column('start_datetime', sa.String(length=20), nullable=True),
    sa.Column('end_datetime', sa.String(length=20), nullable=True),
    sa.Column('departure', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_details',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('quote_id', sa.String(length=10), nullable=False),
    sa.Column('run_date', sa.String(length=10), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.String(length=10), nullable=True),
    sa.Column('includes', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('region_surcharge', sa.Integer(), nullable=True),
    sa.Column('use_time', sa.String(length=20), nullable=True),
    sa.Column('extra_time', sa.Integer(), nullable=True),
    sa.Column('time_surcharge', sa.Integer(), nullable=True),
    sa.Column('lodging_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_details',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('order_id', sa.String(length=10), nullable=False),
    sa.Column('run_date', sa.String(length=10), nullable=True),
    sa.Column('vehicle_id', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('region_surcharge', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('extra_time', sa.Integer(), nullable=True),
    sa.Column('time_surcharge', sa.Integer(), nullable=True),
    sa.Column('lodging_fee', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.String(length=10), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('base_pay', sa.Integer(), nullable=True),
    sa.Column('driver_extra_time', sa.Integer(), nullable=True),
    sa.Column('driver_time_surcharge', sa.Integer(), nullable=True),
    sa.Column('fuel_cost', sa.Integer(), nullable=True),
    sa.Column('fuel_card', sa.String(length=10), nullable=True),
    sa.Column('toll_fee', sa.Integer(), nullable=True),
    sa.Column('toll_card', sa.String(length=10), nullable=True),
    sa.Column('parking_fee', sa.Integer(), nullable=True),
    sa.Column('parking_card', sa.String(length=10), nullable=True),
    sa.Column('meal_fee', sa.Integer(), nullable=True),
    sa.Column('meal_card', sa.String(length=10), nullable=True),
    sa.Column('lodging_pay', sa.Integer(), nullable=True),
    sa.Column('lodging_card', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['operation_orders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_details')
    op.drop_table('quote_details')
    op.drop_table('operation_orders')
    op.drop_table('ledger')
    op.drop_table('quotes')
    op.drop_table('drivers')
    op.drop_table('vehicles')
    op.drop_table('settings')
    op.drop_table('payment_accounts')
    op.drop_table('clients')
    op.drop_table('account_subjects')
    # ### end Alembic commands ###
