"""add product_type to operation_details

Revision ID: eb4cbdd6665f
Revises: 52bda7cd3cfa
Create Date: 2026-06-23 09:00:02.091290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4cbdd6665f'
down_revision = '52bda7cd3cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_details', schema=None) as batch_op:
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
